### ISSUE TITLE
Can't install module on mac m1

### ISSUE THREAD

**Issue by kudryavtsevda** [scottdurow/dataverse-auth#29]
Hi, I am trying to install on my mac m1 via `npm install -g dataverse-auth` and experience this error related to electron package.
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/4447809/181362601-765008a1-baff-4b0c-805e-86f170fd0e14.png">
If I try to install `npm install dataverse-auth` it finishes with the same error.
Could you help me?

**Comment by scottdurow** [comment]
Hi @kudryavtsevda 
Does it work if you use:
`npx dataverse-auth <org url>`

The package doesn't need to be installed using npm install.

**Comment by kudryavtsevda** [comment]
Hi @scottdurow 
I tried this command `npx dataverse-auth <my-url>
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/4447809/181368691-e000a3b3-3fa5-437f-865e-7033ea678875.png">
it asks me to install packaged. But nothing happen when I tries to use `npx dataverse-gen` it says "Run 'npx dataverse-auth' to add a new Microsoft Dataverse envrionment" 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/4447809/181369352-960f5afe-06b6-4f52-915b-139c8a076e3f.png">
So it is inifinite loop for me.
On windows pc it works well that is why I use windows os just for generation purpose.

**Comment by scottdurow** [comment]
Thanks @kudryavtsevda  - I think this is because the M1 is arm based and the electron version being used doesn't support it.

could you try:
`npx dataverse-auth@beta <org url>`

**Comment by kudryavtsevda** [comment]
Hi @scottdurow 

It works for me, then I use `npm dataverse-gen@beta` to resfresh metadata.

Thank you for your assistance.

**Comment by scottdurow** [comment]
Hi @kudryavtsevda - Thank you for testing and confirming that the latest beta works.

As you've discovered - you need to use the latest beta of dataverse-gen with the beta of dataverse-auth - however, there are a number of bugs that still need to be fixed which I'll hopefully get to in the next few days.

I'll post here once we have a stable beta.
